Add support for seccomp notify
Runtime spec has just merged support for seccomp notify:
        https://github.com/opencontainers/runtime-spec/commit/a8c4a9ee0f6b5a0b994c5c23c68725394e2b0d9d

In containerd what we have to do to support it is just updating the
vendoring to point to the new version. This version add the json tags to
the struct, so the current code that copies this to the config.json file
needs no change:
        https://github.com/containerd/containerd/blob/8dbe53a2a930af3631229e4d92cf839b64ee5a38/contrib/seccomp/seccomp.go#L36-L40

We just use the json.Unmarshal there that handles the new fields.

Please note that a PR for runc is open for some time by a coworker, I'll
update it and ask for review:
        https://github.com/opencontainers/runc/pull/2682

However, if containerd uses an runc without support for seccomp notify,
no issues are seen if we use a seccomp profile with the new field. When
doing that, we just see this error when creating a container from kubectl
describe pod:
	Error: failed to create containerd task: OCI runtime create failed: string SCMP_ACT_NOTIFY is not a valid action for seccomp: unknown

Something similar is shown if the container is created with crictl.

TODO: test if the other spec change also doesn't create issues